apiVersion : apps/v1
kind: Deployment
metadata:
  name: aksdebug-deployment
  labels:
    app: yuehingyuaksdebug
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yuehingyuaksdebug
  template:
    metadata:
      labels:
        app: yuehingyuaksdebug 
    spec:
      containers:
        - name: yuehingyuaksdebug 
          image: yycontainerregistry2022.azurecr.io/yuehingyuaksdebug
          ports:
          - containerPort: 8080
